@startuml jiro

object 次郎 #yellow {
  1968-1972(移転閉店)
  都立大学
}

object 二郎 #yellow {
  (移転改名)1972-1996/2/29
  三田
}

object 三田本店 #yellow {
  (移転改名)1996/6/5-
  三田
}

object 吉祥寺 #yellow {
  1986-2001/4
}

object 生郎 {
  (改名・脱退)→2015/4閉店
}

object 堀切 #yellow {
  1998/7/28-2001/10/31
}

object 一代 {
}

object ぽっぽっ屋 {
}

object どっと屋 {
}

object 暖々 {
}

object 大者 {
  2010/12/1(店長が脱退独立)
}

object 大 {
}

object 赤羽_旧 #yellow {
  1991/2/15-2001
}

object 赤羽_移転 #yellow {
  2012/1/29-2017/4/30閉店
}

object O二郎 {
  2001改名→富士丸
}

object 富士丸 {
  2007/8改名
}

object 目黒 #yellow {
  1995/7-
}

object 仙川_前 #yellow {
  1995/10/16-2004/9/7・店主逝去
}

object 仙川_現 #yellow {
  2005/1/17-
}

object 環七新代田_前 #yellow {
  2000/1/30-2014/4/26
}

object 京急川崎 #yellow {
  2001/4/25-
}

object 鶴見 #yellow {
  1996/2-2013/3休業→2013/9
  JR西口蒲田に移転閉店
}

object 武蔵小杉 #yellow {
  1996/5-店主退転
}

object 歌舞伎町 #LightBlue {
  1997/8/11-2016/8/28
  NS系
}

object 八王子野猿街道 #yellow {
  2000/8/28-2006/5/20
}

object 八王子野猿街道2 #yellow {
  移転改名2006/6/10-
}

object 新宿歌舞伎町 #LightBlue {
  移転改名2016/10/3-
  NS系
}

object 京成大久保_前 #yellow {
  2002/12/16-2007/06/30
}

object 京成大久保_改築 #yellow {
  2008/9/11-
}

object 池袋東口 #LightBlue {
  2001/2/9-
  NS系
}

object 神田神保町_前 #yellow {
  フーズ神田出身2004/11/06-2017/11/25
}

object 神田神保町_移転 #yellow {
  2017/12/11-
}

object 京都 #yellow {
  2017/4/2-
}

object 一橋学園 #yellow {
  2022/8/11-
}

object 品川_直系移行 #yellow {
  2001-2010/7/13
}

object 品川_改装 #yellow {
  2010/8/24-
}

object 新宿小滝橋通り #yellow {
  1999/2/8-フーズ代々木から脱退？
}

object 上野毛_前 #yellow {
  店主引退2002/11/12-2006/8/20
}

object 上野毛_現 #yellow {
  2006/8/21-
}

object 小岩 #yellow {
  2005/11/6-
}

object 千住大橋駅前 #yellow {
  2009/4/19-
}

object 新橋 #LightBlue {
  2011/9/18-2018/4/21閉店
  NS系
}

object ひたちなか #yellow {
  2021/12/12-
}

object 松戸駅前_初代 #yellow {
  2002/05/12-2011/9/29移転閉店
}

object 松戸駅前_前 #yellow {
  前・2012/3/20-2015/7/26移転閉店
}

object 松戸駅前_現 #yellow {
  2015/8/9-
}

object 新潟 #yellow {
  移転2015/11/8-
}

object 環七新新代田 #yellow {
  現2014/5/18-
}

object 526武蔵小杉 {
  2011/1/19脱退改名
}

object 町田 #yellow {
  1999/3/9-2002/9/29閉店
}

object JR西口蒲田 #yellow {
  移転改名2014/11/7-2019/10/11閉店
}

object 登良治郎 {
  2017/4/15-
}

object 横浜関内 #yellow {
  2004/10/11-
}

object 桜台 #yellow {
  2007/1/14-
}

object 札幌 #yellow {
  2013/3/31-
}

object 荻窪_現 #yellow {
  2016/1/17-
}

object HERO {
  2022/6/5-
}

object 湘南藤沢 #yellow {
  2010/3/14-
}

object 越谷 #yellow {
  2019/3/10-
}

object 亀戸_前 #yellow {
  2001/4/17-2013/3/31
}

object 亀戸_現 #yellow {
  2013/4/14-
}

object 環七一之江 #yellow {
  2003/11/16-
}

object 新小金井街道_旧 #yellow {
  2001/3/31-2003/5/19
}

object 新小金井街道_移転 #yellow {
  2003/5/27-2018/5/27引退
}

object 新小金井街道_臨時再開 #yellow {
  2018/6/24-2018/12/23閉店
}

object 相模大野駅前 #yellow {
  2003/12/7-2009/5/24
}

object 相模大野 #yellow {
  移転改名2009/6/23-
}

object ひばりヶ丘駅前 #yellow {
  2006/6/11-
}

object 仙台 #yellow {
  2011/10/23-
}

object 前橋千代田町 #yellow {
  2019/10/27-
}

object 生田駅前 #yellow {
  2023/5/21-
}

object 栃木街道 #yellow {
  2007/11/25-
}

object 会津若松駅前 #yellow {
  2014/9/21-
}

object 中山駅前 #yellow {
  2010/12/12-
}

object 川越 #yellow {
  2017/3/19-
}

object BooBoo太郎 {
  2016/10/15-
}

object ピース {
  2021/11/14-
}

object 元気の源_閉店 {
}

object 2号神奈川新町_閉店 {
}

object めじろ台法政大学前 #yellow {
  2002/5/25-2017/5/13
}

object めじろ台_移転改名 #yellow {
  2017/5/28-2023/2/28廃業
}

object めじろ台_現 #yellow {
  2023/6/18-
}

object 荻窪_前 #yellow {
  2002/10/14-2014/1
}

object 立川_旧 #yellow {
  2008/04/27-2014/3休業
}

object 立川_再開 #yellow {
  2018/2/20再開-2020/6/15休業→引退
}

object 立川_現 #yellow {
  2023/1/29-
}

object 府中 #yellow {
  2001/5/1-2006/3/26→移転2006/5/3-
}

object 高田馬場_旧 #yellow {
  2002/5/9-2009/12/24
}

object 高田馬場_移転 #yellow {
  2010/1/6-2012/12休業→2013/3閉店
}

object 大宮 #yellow {
  2008/08/24-2016/11/30閉店
}

object 大宮公園駅前 #yellow {
  2020/6/5-
}

object 茨城守谷 #yellow {
  2009/06/07-2022/12/9移転閉店
}

object 柏 #yellow {
  移転2023/1/9-
}

object 西台駅前 #yellow {
  2010/6/27-
}

object 千葉 #yellow {
  2020/6/2-
}

object 虎ノ門 #green {
  1996/9/11-2004/10/31
  ジローフードシステム
}

object ラーメン虎ノ門 #green {
  2004/11/1-2020/1閉店
  ジローフードシステム
}

object 新橋_前 #green {
  1996/9/11-2004/7/5
  ジローフードシステム
}

object ラーメン新橋 #green {
  2004/7/6-2018/4/21閉店
  ジローフードシステム
}

object 品川_前 #green {
  1997/10-2001
  ジローフードシステム
  →脱退・直系加入
}

object 蒲田 #green {
  1997/12/15-2001/10/31
  ジローフードシステム
  →脱退・堀切系移行→ラーメン大
}

object 神田 #green {
  1998/4/15
  ジローフードシステム
  →ラーメン神田店
}

object ラーメン神田 #green {
  ジローフードシステム
}

object 代々木 #green {
  1998/9/25
  ジローフードシステム
}



次郎 --> 二郎
二郎 --> 吉祥寺
二郎 --> 三田本店
二郎 --> 赤羽_旧
二郎 --> 鶴見
二郎 --> 武蔵小杉


三田本店 --> 歌舞伎町
三田本店 --> 八王子野猿街道
三田本店 --> 亀戸_前
三田本店 --> 上野毛_前
三田本店 --> めじろ台法政大学前
三田本店 --> 荻窪_前
三田本店 --> 府中
三田本店 --> 高田馬場_旧
三田本店 --> 京成大久保_前
三田本店 --> 神田神保町_前
三田本店 --> 品川_直系移行
三田本店 --> 新宿小滝橋通り


品川_前 --> 品川_直系移行
品川_直系移行 --> 品川_改装

京成大久保_前 --> 京成大久保_改築
神田神保町_前 --> 京都
神田神保町_前 --> 神田神保町_移転
神田神保町_前 --> 一橋学園

めじろ台法政大学前 --> めじろ台_移転改名
鶴見 --> 横浜関内
鶴見 --> 元気の源_閉店
鶴見 --> 新小金井街道_旧
鶴見 --> JR西口蒲田
武蔵小杉 --> 526武蔵小杉
武蔵小杉 --> 町田
歌舞伎町 --> 新宿歌舞伎町
歌舞伎町 --> 環七新新代田
歌舞伎町 --> 池袋東口

八王子野猿街道 --> 八王子野猿街道2
八王子野猿街道 --> 新小金井街道_旧
八王子野猿街道 --> 栃木街道
八王子野猿街道 --> 会津若松駅前
八王子野猿街道 --> 松戸駅前_現
八王子野猿街道 --> めじろ台_現

新小金井街道_旧 --> 新小金井街道_移転
新小金井街道_旧 --> 相模大野駅前
新小金井街道_旧 --> ひばりヶ丘駅前
新小金井街道_移転 --> 中山駅前
新小金井街道_旧 --> 仙台
新小金井街道_旧 --> 前橋千代田町
新小金井街道_旧 --> 生田駅前
新小金井街道_移転 --> 新小金井街道_臨時再開
相模大野駅前 --> 相模大野

池袋東口 --> 亀戸_前
亀戸_前 --> 上野毛_前
亀戸_前 --> 松戸駅前_初代
松戸駅前_初代 --> 赤羽_移転
亀戸_前 --> 環七一之江
環七一之江 --> 千住大橋駅前
環七一之江 --> 立川_現

上野毛_前 --> 小岩
上野毛_前 --> 上野毛_現
上野毛_前 --> 立川_旧
立川_旧 --> 立川_再開
小岩 --> 千住大橋駅前
池袋東口 --> 新橋
新橋 --> ひたちなか
池袋東口 --> 松戸駅前_前
松戸駅前_前 --> 新潟

JR西口蒲田 --> 登良治郎
元気の源_閉店 --> 2号神奈川新町_閉店
横浜関内 --> 桜台
横浜関内 --> 湘南藤沢
横浜関内 --> 川越
横浜関内 --> BooBoo太郎
横浜関内 --> ピース
湘南藤沢 --> 越谷
横浜関内 --> 亀戸_現
桜台 --> 札幌
桜台 --> 荻窪_現
桜台 --> HERO
赤羽_旧 --> O二郎
赤羽_旧 --> 目黒
赤羽_旧 --> 仙川_前
仙川_前 --> 仙川_現
赤羽_旧 --> 環七新代田_前
赤羽_旧 --> 京急川崎
O二郎 --> 富士丸
吉祥寺 --> 生郎
吉祥寺 --> 堀切
堀切 --> 蒲田
蒲田 --> 大
堀切 --> 一代
堀切 --> ぽっぽっ屋
堀切 --> どっと屋
堀切 --> 暖々
堀切 --> 大
暖々 --> 大
暖々 --> 大者

高田馬場_旧 --> 高田馬場_移転
高田馬場_旧 --> 大宮
高田馬場_旧 --> 茨城守谷
茨城守谷 --> 柏
高田馬場_旧 --> 西台駅前
西台駅前 --> 千葉
大宮 --> 大宮公園駅前

虎ノ門 --> ラーメン虎ノ門
神田 --> ラーメン神田
新橋_前 --> ラーメン新橋





@enduml